### ISSUE TITLE
Describe new features

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#2615]
- [x] Run TestCafe over https protocol (https://github.com/DevExpress/testcafe/issues/1985#issuecomment-389488983)
I've created a topic draft for this feature. See - https://github.com/miherlosev/tmp/issues/9
- [x] Screenshot file pattern (https://github.com/DevExpress/testcafe/pull/2086#issuecomment-365604782)
- [ ] No reload page url between tests (https://github.com/DevExpress/testcafe/issues/1770)
 - [x] Debug mode with non-modified client scripts (https://github.com/DevExpress/testcafe/issues/2545)
