### ISSUE TITLE
Document all pre-2.0 proposals with breaking changes

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3057]
Use this issue to create a list of all proposals and enhancements, that we want to see in `testcafe@1.0.0` and can introduce breaking changes after implementation.

⭐️ General 
 - [ ] Use the `@testcafe` scope for all TestCafe packages (#2807)
 - [ ] Run each browser job in a separate process
 - [x] Remove flag to disable syntax test checking

✅ Tests API
- [ ] Deprecate selector snapshots (from https://github.com/DevExpress/testcafe/issues/3082)
- [ ] Deprecate `eval ` action (from https://github.com/DevExpress/testcafe/issues/3082)
- [ ] Wrap all [DOM Node state](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/dom-node-state.html) properties with [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to allow calling methods and accessing subproperties in Smart Assertions.
 - [x] Pass the value of "prompt" dialog's input to the native dialog handler (#2667)
 - [x] Async onRequest / onResponse methods for hooks (#2816)
 - [x] Refactor RequestLogger configuration options (#2658)
 - [ ] Implement BDD interface and nested fixtures (#792)
 - [ ] Import `fixture` and `test` from 'testcafe' (#1735)
 - [ ] Introduce more convenient syntax for redefining options in parameterized Selectors (#2548)

📜 Runner API
 - [ ] Move parameters of `createTestCafe` to single `options` parameter (#2786)
 - [ ] Modify Runner API to allow using browser automation features without tests
 - [ ] Modify Runner API to allow running tests without any browser

💻 CLI
 - [x] Use a config file instead of complex CLI options
 - [ ] Add two char shortcuts for all multiword command line options

🖨 Reporters
 - [ ] Rework the `xunit` reporter to don't report variable test metadata (screenshot paths, unstable flag, etc.) in test names. (https://github.com/DevExpress/testcafe-reporter-xunit/issues/2) 
 - [x] Add a way to handle warning messages in the real time (#2753)
 - [x] Make Reporter API asynchronous (#2753)
 - [x] Change the method of calculating the number of passed/failed tests (#2753)

🌐 Browser providers
 - [ ] Implement an API for batch running (see DevExpress/testcafe-browser-provider-browserstack#18)
 - [ ] Remove the second argument of the `BrowserProviderPlugin.isLocalBrowser`
 - [ ] Refactor BrowserProviderPlugin feature-detection methods (`isLocalBrowser`, `isHeadlessBrowser`, `hasCustomActionForBrowser`)

:shipit: Other plugins & tools
- [x] Integrate TestCafe Live to the main TestCafe code
- [ ] Rename the `reporter` option to `reporters` in `gulp-testcafe`.

**Comment by AndreyBelym** [comment]
- [ ] getting selector snapshot 
But in this case we need capability to compare part of element properties with some object, e.g.
```js
await t.expect(Selector('input')).containsProperties({ classNames: 'some-class', innerText: 'some text' });
```
- [ ] `eval ` action

**Comment by AndreyBelym** [comment]
https://github.com/DevExpress/testcafe-reporter-xunit/issues/2

 - [ ] Rework the `xunit` reporter to don't report variable test metadata (screenshot paths, unstable flag, etc.) in test names.

**Comment by AndreyBelym** [comment]
- [ ] Remove the second argument of the BrowserProviderPlugin.isLocalBrowser
 - [ ] Refactor BrowserProviderPlugin feature-detection methods (isLocalBrowser, isHeadlessBrowser, hasCustomActionForBrowser)

**Comment by AndreyBelym** [comment]
- [ ] Integrate TestCafe Live to the main TestCafe code
