### ISSUE TITLE
Write a specification for the Selector debug panel feature 

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3789]
We need to write a detailed specification for the [Selector Debug Panel (#3244)](https://github.com/DevExpress/testcafe/issues/3244) feature and discuss it among the team members.

**Comment by AndreyBelym** [comment]
Subgoals:
- [ ] Move the compilator and compiled code to a separate process (https://github.com/DevExpress/testcafe/issues/3810)
- [ ] Apply `--inspect-brk` and other V8 flags to the compilator process (https://github.com/DevExpress/testcafe/issues/3811)
- [ ] Implement a synchronous Selector API (https://github.com/DevExpress/testcafe/issues/3812)
