### ISSUE TITLE
Workflow & Repository Suggestions

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4100]
- [ ] Switch to a monorepo, use [Lerna](https://www.npmjs.com/package/lerna)
 - [x] Build an NPM package for all PRs and commits to `master`
 - [x] Automatically post notifications to issue threads when we publish a release that fixes related issues
 - [ ] Daily integration tests - https://github.com/DevExpress/testcafe/issues/3143 
 - [ ] Test our docker image for all PRs and commits - https://github.com/DevExpress/testcafe/issues/1564
 - [ ] Automate our Docker image builds and achive the `official` status in Docker Hub - https://github.com/DevExpress/testcafe/issues/3066
 - [ ] Make easier searching duplicates in the repo issues
 - [ ] Do not hardcode dependencies - https://github.com/DevExpress/testcafe/issues/5251
