### ISSUE TITLE
Find ways to improve UX with test API

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5087]
Our feedback stats show that our customers have some difficulties with our asynchronous APIs sometimes. We should find a way to make our API easier to use or improve diagnostics to report "missing await" and so on as early as possible.
 - [ ] Selector filters and expressions (need more examples)
 - [ ] ClientFunction use cases (need more examples)
 - [x] `Selector.exists` is not used to check existence (https://github.com/DevExpress/testcafe/pull/5211)
 - [x] Detailed diffs (#5255)
 - [x] DOM snapshot property `await Selector` is used in assertions (#5250)
 - [x] missing `await`s for DOM node snapshots (`if` branches, working with element text) (#5383)
 - [ ] the problematic `allowUnawaitedPromise` option [[1](https://github.com/DevExpress/testcafe/issues/4767)]
