### ISSUE TITLE
[docs] Describe TestCafe current limitations

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5196]
We should clearly describe our current technical limitations:
- [x] 1. ClientFunction dependencies must be Selectors, ClientFunctions or a serializable object [[1](https://stackoverflow.com/questions/60961748/clientfunction-axios2-is-not-defined )]
 - [x] 2. TypeScript cannot detect ClientFunction and Selector dependencies inside the ClientFunction scope [[1]](https://stackoverflow.com/questions/57983950/customize-testcafe-selector-in-typescript-for-shadow-root-element )
 - [x] 3. Describe features that can't be used in ClientFunctions due to transpilation: property shorthands for imported values,...
 - [x] 4. Stable functionality on zoomed in our out pages is not guaranteed
 - [x] 5. `t.pressKey` combinations for Ctrl + "+"/Ctrl + "-" don't zoom in our out [[1]](https://stackoverflow.com/questions/60347248/is-there-a-way-to-achieve-key-combination-ctrl-using-testcafe)
 - [x] 6. Native dialogs are not shown during a testing session [[1](https://github.com/DevExpress/testcafe/issues/4776)]
 - [x] 7. Relative URLs are not supported in Roles [[1]](https://github.com/DevExpress/testcafe/issues/3406)
 - [x] 8. Problems with imported TestControllers in compiled modules [[1](https://github.com/DevExpress/testcafe/issues/3526)]
 - [x] 9. There is no point to pass an imported TestController to Selectors and ClientFunctions via the `boundTestRun` property [[1](https://stackoverflow.com/questions/57228588/selector-cannot-find-test-controller)]
 - [x] 10. RequestMocks must be used to avoid problems with file downloading in IE11 [[1](https://stackoverflow.com/questions/56942819/testcafe-click-spawned-pop-up-to-save-csv-file )]
- [x] 11. Smart assertions auto retry feature only works with Promises returned only from ClientFunctions, Selectors properties, and some RequestLogger properties. using `await` is prohibited [[1](https://stackoverflow.com/questions/55299919/testcafe-seems-not-working-a-combination-of-expect-exists-okor-notok )] 
- [x] 12. Smart assertions auto retry feature doesn't work with `RequestLogger.requests.length` property [[1](https://stackoverflow.com/questions/57504689/what-the-difference-between-assertion-timeout-and-wait-method)]
- [x] 13. Describe conditions when TestCafe actions will fail to execute or take time to retry, including visibility problems [[1](https://stackoverflow.com/questions/57382559/testcafe-how-to-typetext-into-hidden-input-for-spectrum-color-picker)]
- [x] 14. Note that special HTML space characters (like `&nbsp;`, newline chars) need special representation when using `Selector.withText` and so on [[1](https://stackoverflow.com/questions/56757405/is-there-any-way-to-click-the-sign-in-link-on-github-page-using-javascript-for )]
- [x] 15. Selector can select multiple elements, but only the first element will be used for actions and when retrieving DOM node snapshots [[1](https://stackoverflow.com/questions/56023183/is-there-any-way-to-find-the-runtime-values-of-a-selector-with-testcafe-and-vs-c)]
- [x] 16. Request Hooks and Dialog Handlers that are expected to be active during the initial test page load should be used with an empty test page and added before calling `navigateTo` to the target page, or added via declarative `test` & `fixture` syntax (for hooks). 
- [x] 17. `headless` and `emulation` browser modes don't work well together with the `userProfile` mode.
 - [x] 18. Github Actions runner on Mac OS cannot run tests due to the security mechanism [[1]( https://github.com/DevExpress/testcafe/issues/5352#issuecomment-663601252)]

**Comment by wentwrong** [comment]
Regarding limitation "18. Github Actions runner on Mac OS cannot run tests due to the security mechanism": 
I shared [here](https://stackoverflow.com/a/63355065/13791235) a simple workaround with tests in remote mode on Github Actions. If you run tests in this way, it doesn't matter whether SIP is turned on because the remote mode doesn't use a platform-specific functionality (screenshots and resizing). I posted a link to the repo with an example in the comment below my answer on StackOverflow.
