### ISSUE TITLE
Improve missing `await` tracking system

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#525]
- [ ] Handle cases then error can be caused by missing `await`, e.g.:

``` js
t.click('#checkbox');
expect(await Selector('#checkbox').checked).to.be.true;
```

Place missing await error before the actual error in report, because it may give a hint about a cause of actual error.
- [ ] Handle missing awaits for ClientFunctions
- [ ] Handle missing awaits for Selector
- [ ] Handle missing awaits for Selector snapshot shorthand properties and methods

**Comment by inikulin** [comment]
Blocked on #524 because it will introduce new machinery by passing hybrid results to action

**Comment by inikulin** [comment]
Still not sure about this one. Moved to proposals until we will not get some feedback
