### ISSUE TITLE
[docs] Update Roadmap

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#6250]
- [ ] Change scroll actions status
- [ ] Mouse Actions (mouseDown, mouseUp, etc.)﻿ status
- [ ] Implement HTTP/2 support status
- [ ] Implement HTTP caching status
- [ ] Add links to the versions for features with the Implemented status
