### ISSUE TITLE
Node snapshot properties shorthands for Selector

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#771]
# Feature summary
For @DevExpress/testcafe-docs 
**Important:** We need to update all docs examples to use this approach.

### Shorthands
If you need to obtain just single property from snapshot you need to use two assignments:
```js
const snapshot = await selector();
const nodeType = snapshot.nodeType;
```
or use awkward single-line expression which is hard to write and read due to lots of parenthesis:
```js
const nodeType = (await selector()).nodeType;
```

This features introduces shorthands - async snapshot property getters on selector itself (and selector promise as well), so now you can write:
```js
const nodeType = await selector.nodeType;

// Selector promise has shorthands as well - useful for parametrized selectors
const nodeType = await selector('someParam').nodeType;
```

You can obtain all first-level snapshot properties this way.

### Dictionary shorthand methods

Snapshots contain some useful dictionaries: `style`, `attributes`, `boudingClientRect`. But even with shorthands we can't obtain their keys in single expression:
```js
const width = (await selector.style)['width'];
``` 
So we introduce 3 shorthand methods for this dictionaries: `getStyleProperty`, `getAttribute`, `getBoundingClientRectProperty`:
```js
const width = await selector.getStyleProperty('width');
const id = await selector.getAttribute('id');
const left = await selector.getBoundingClientRectProperty('left');
```

### hasClass

In addition we added `hasClass` method:
```js
if (await selector.hasClass('yo')) {
  ...
}
```

# Original proposal 

Currently, you need to re-select node to get access to it's snapshot properties, so you may end up with awkward constructs which involves `await`, e.g.:
```js
test('Moving the slider', async t => {
    const initialOffset = (await page.slider.handle()).offsetLeft;

    await t
        .click(page.triedTestCafeCheckbox)
        .dragToElement(page.slider.handle, page.slider.tick.with({ text: '7' }));

    const newOffset = (await page.slider.handle()).offsetLeft;

    expect(newOffset).gt(initialOffset);
});
```

The idea is to expose snapshot properties on `Selector` which will return promise for the given propety value (it will execute selector and return required property under the hood), so we will have:
```js
test('Moving the slider', async t => {
    const initialOffset = await page.slider.handle.offsetLeft;

    await t
        .click(page.triedTestCafeCheckbox)
        .dragToElement(page.slider.handle, page.slider.tick.with({ text: '7' }));

    const newOffset = await page.slider.handle.offsetLeft;

    expect(newOffset).gt(initialOffset);
});
```

\cc @DevExpress/testcafe 
What do you guys think?

**Update note:**
This will really play well with [chai-as-promised](http://chaijs.com/plugins/chai-as-promised/) assertions.

**TODO:**
- [x] Shorthands on selector
- [x] `getStyleProperty`
- [x] `getAttribute`
- [x] `getBoundingClientRectProperty`
- [x] `hasClass`
- [x] Shorthands on selector result promise (parametrized selectors)
- [x] Error for selector not matching any node
- [x] Proper callsites for selector errors (basic and parametrized)

**Comment by AlexanderMoskovkin** [comment]
Just for sure, am I understood your proposal right?
```js
var bodySelector = Selector(() => document.body);
var getBodyOffsetWidth = bodySelector.offsetWidth;

var bodySnapshot = await bodySelector();
var bodyWidth1 = bodySnapshot.offsetWidth;
var bodyWidth2 = await getBodyOffsetWidth();
```
in this case `bodyWidth1 === bodyWidth2`

**Comment by inikulin** [comment]
@AlexanderMoskovkin 

> Just for sure, am I understood your proposal right?

Ehh, not sure about it =) Speaking clearly, instead of:
```js
const elSelector = Selector('#someElem');

const el = await elSelector();

const offset = el.offsetLeft;
```
you'll be able to write
```js
const elSelector = Selector('#someElem');

const offset = await elSelector.offsetLeft;
```

**Comment by AlexanderMoskovkin** [comment]
got is. Looks useful

**Comment by miherlosev** [comment]
Can we just drop `await` keyword before Selector properties access?

**Comment by VasilyStrelyaev** [comment]
looks nice

**Comment by inikulin** [comment]
@miherlosev No, how you imagine that?

**Comment by miherlosev** [comment]
When test code performs access to selector properties we perform sync request to client, getting result from client and execute next statement from test code.

**Comment by georgiy-abbasov** [comment]
The approach is more common, as it was before. I like it

**Comment by inikulin** [comment]
> When test code performs access to selector properties we perform sync request to client

Cool cool, but I have no idea how we can perform "sync request to client"

**Comment by helen-dikareva** [comment]
it looks good, but we should explain in docs differece between using snapshot (not recalculate selector) and this mechanism

**Comment by miherlosev** [comment]
Ok. I don't know internal implementation. It just view from the outside.

**Comment by inikulin** [comment]
@miherlosev It's not about internal implementation. We use hammerhead for messaging. Does it support sync communication with client?

**Comment by kirovboris** [comment]
> What do you guys think?

:+1:  I like it.

**Comment by miherlosev** [comment]
> It's not about internal implementation. We use hammerhead for messaging. Does it support sync communication with client?
Now it does not suppoeted. We can investigate it.

**Comment by inikulin** [comment]
@miherlosev Where is no sync request API in modern browsers. There is sync XHR but it's extremely buggy and deprecated.
